name: Cypress Tests

# on:
#   push:
#     branches:
#       - main  # Adjust this to your branch
#   pull_request:
#     branches:
#       - main  # Adjust this to your branch
on: workflow_dispatch

jobs:
  cypress-tests:
    runs-on: ubuntu-latest  # You can change the OS if necessary

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Set to your desired Node.js version

    - name: Install dependencies
      run: |
        npm install

    - name: Run Cypress tests
      run: |
        npx cypress run