name: K6 Load Testing Workflow
on: workflow_dispatch
jobs:
  k6_load_test:
    name: K6 Load Test Run
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3
      # Step 2: Set up K6
      - name: Install K6
        uses: grafana/setup-k6-action@v1
        with:
          flags: --out json=results.json
      # Step 3: Run K6 load test
      - name: Run K6 Test
        run: k6 run ./test-scripts/k6-loadtesting/loadtestingscript.js
